//
//  jobsPresenter.swift
//  StackTracker
//
//  Created by Kayode Hadilou ADJE on 8.09.2018.
//  Copyright (c) 2018 Kayode Hadilou ADJE. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import mang_utility

protocol IjobsPresentationLogic: ICatchError {
    func presentSomething(response: jobs.Something.Response)
}

class jobsPresenter: IjobsPresentationLogic {
    weak var viewController: IjobsDisplayLogic?

    init (viewController: IjobsDisplayLogic?) {
        self.viewController = viewController
    }

    // MARK: ICatchError
    func catchError() {
        catchError(error: nil)
    }
    func catchError(error: Error?) {
        self.viewController?.hideLoading()
        self.viewController?.catchError(error: error)
    }
        
    // MARK: Do something

    func presentSomething(response: jobs.Something.Response) {
        let viewModel = jobs.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
}
