//
//  jobsViewController.swift
//  StackTracker
//
//  Created by Kayode Hadilou ADJE on 8.09.2018.
//  Copyright (c) 2018 Kayode Hadilou ADJE. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import mang_utility
import mang_ui_controls

protocol IjobsDisplayLogic: class, ILoading, IAlert, ICatchError {
    func displaySomething(viewModel: jobs.Something.ViewModel)
}

class jobsViewController: BaseViewController, IjobsDisplayLogic {
    var interactor: IjobsBusinessLogic?
    var router: (NSObjectProtocol & IjobsRoutingLogic & IjobsDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }

    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
    }

    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        self.router?.prepare(for: segue, sender: sender)
    }

    // MARK: View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doSomething() {
        let request = jobs.Something.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: jobs.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }  
}
