//
//  jobsRouter.swift
//  StackTracker
//
//  Created by Kayode Hadilou ADJE on 8.09.2018.
//  Copyright (c) 2018 Kayode Hadilou ADJE. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IjobsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func prepare(for segue: UIStoryboardSegue, sender: Any?)
}

protocol IjobsDataPassing {
    var dataStore: IjobsDataStore? { get }
}

class jobsRouter: NSObject, IjobsRoutingLogic, IjobsDataPassing {
    weak var viewController: jobsViewController?
    var dataStore: IjobsDataStore?

    init(viewController: jobsViewController?, dataStore: IjobsDataStore?) {
        self.viewController = viewController
        self.dataStore = dataStore
    }

    // MARK: Routing

    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    //func navigateToSomewhere(source: jobsViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    //func passDataToSomewhere(source: jobsDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
    
    // MARK: IjobsRoutingLogic implementation
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    }    
}
